/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "bar_alternativetags.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tags.c"
#include "bar_flexwintitle.c"
#include "bar_wintitle_floating.c"
#include "bar_wintitle_hidden.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusdir.c"
#include "killunsel.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "swaptags.c"
#include "switchcol.c"
#include "tagothermonitor.c"
#include "togglefullscreen.c"
#include "transferall.c"
#include "vanitygaps.c"
#include "warp.c"
#include "winview.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_flextile-deluxe.c"

