/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tags.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "focusdir.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "inplacerotate.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "killunsel.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_tile.c"

