/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_anybar.c"
#include "combo.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusdir.c"
#include "inplacerotate.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "killunsel.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "swaptags.c"
#include "switchcol.c"
#include "tagothermonitor.c"
#include "togglefullscreen.c"
#include "transferall.c"
#include "vanitygaps.c"
#include "winview.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_flextile-deluxe.c"

