/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_anybar.h"
#include "combo.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusdir.h"
#include "inplacerotate.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "killunsel.h"
#include "nomodbuttons.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "selfrestart.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "swaptags.h"
#include "switchcol.h"
#include "tagothermonitor.h"
#include "togglefullscreen.h"
#include "transferall.h"
#include "vanitygaps.h"
#include "winview.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"

