#!/bin/sh
toggle_brightness() {
	if [ "$(xbacklight -get)" -gt "70" ]; then
		xbacklight -set 1 -fps 30
	elif [ "$(xbacklight -get)" -lt "19" ]; then
		xbacklight -set 25 -fps 30
	elif [ "$(xbacklight -get)" -lt "70" ] && [ "$(xbacklight -get)" -gt "20" ]; then
		xbacklight -set 75 -fps 30
	fi
}

case $BLOCK_BUTTON in
1) toggle_brightness ;;
2) notify-send "🔆 Brightness module" "Displays brightness level
- Left click to toggle brightness
- Middle click to set at minimum brightness
- Scroll to change." ;;
3) xbacklight -set 1 -fps 30 ;;
4) xbacklight -inc 3 ;;
5) xbacklight -dec 3 ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac

BNESS="$(xbacklight -get)"

if [ "$BNESS" -gt "70" ]; then
	icon="🔆"
elif [ "$BNESS" -lt "20" ]; then
	icon="🌘"
else
	icon="🔅"
fi

echo "^c#9ECE6A^^b#32344A^ $icon$BNESS ^d^"
