#!/bin/sh
index=$(pamixer --list-sources | awk '/input/ {print $1}')
mic_muted="$(pamixer --source "$index" --get-mute)"
if [ "$mic_muted" = "true" ]; then
	echo "🎤❌"
else
	echo "🎤⭕"
fi

case $BLOCK_BUTTON in
1) mic-toggle ;;
2) notify-send "🎤 Microphone module" "\- Shows microphone status.
- Left click to mute." ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac
