#!/bin/sh

toggleredshift() {
	pidof redshift >/dev/null && killall redshift || setsid redshift
}

case $BLOCK_BUTTON in
    1) notify-send "$(redshift -p)" ;;
    2) notify-send "💡 Redshift module" "\- Displays current redshift status
    - 🌙 at night.
    - 💡 during transition phase.
    - ☀  when it is day time." ;;
    3) toggleredshift ;;
    # 4)  ;;
    # 5)  ;;
    6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac

# period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"
temperature="$(redshift -p | awk '$0 ~ "Color temperature" {print $3}')"
period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"

case $period in
  "Night") icon="🌙" ;;
  "Transition") icon="💡" ;;
  "Daytime") icon="☀️" ;;
esac

pidof redshift >/dev/null && echo "$icon$temperature" || echo "💡"
